require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.1
  Exclude:
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/assets/**/*
    - node_modules/**/*

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/**/*

Metrics/AbcSize:
  Max: 20
  Exclude:
    - db/migrate/*
    - app/services/maps/*

Lint/MissingSuper:
  Exclude:
    - app/services/**/*

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - lib/tasks/*.rake
    - config/routes.rb
    - config/**/*
    - test/**/*
    - db/seeds.rb

Layout/LineLength:
  Max: 140
  Exclude:
    - Rakefile
    - Gemfile
    - config/**/*
    - lib/tasks/**/*
    - test/test_helper.rb
    - db/migrate/*
    - spec/**/*
  IgnoredPatterns:
    - (\A|\s)#

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/seeds.rb
    - db/migrate/*
    - test/test_helpers/*

Metrics/ClassLength:
  Exclude:
    - db/migrate/*

Metrics/ModuleLength:
  Max: 120

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - test/**/*
    - spec/**/*

Rails/NotNullColumn:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2
